name: CII

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-report
          path: bandit-report.json
          
  image_scan:       
     name: Build Image and Run Image Scan
     runs-on: ubuntu-latest

     steps: 
     - name: Checkout code
        uses: actions/checkout@v2

     - name: Set Up Docker
        use: docker-practice/actions-setup-docker@v1  
        with:
          dockedocker_version: '20.10.7'
          
     - name: Builder Docker Image 
        run: docker build -f Dockerfile -t myapp:latest .

     - name: Docker Scout scan
        run: 
             curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
             sh install-scout.sh

             echo ${{ secrets.MYREPO_PWD }} | docker login -u ${{ secrets.MYREPO_USER }} --password-stdin
             
             docker scout quickview
             docker scout cves

    
        



       
       
    -    

    
